SELECT NO_IMM, MODELE
FROM VEHICULE
WHERE CODE_CATEG LIKE 'c3'
MINUS
SELECT V.NO_IMM, V.MODELE
FROM CALENDRIER C
         INNER JOIN VEHICULE V ON V.NO_IMM = C.NO_IMM
WHERE DATEJOUR BETWEEN to_date('2015-10-25', 'YYYY-MM-DD') AND to_date('2015-10-25', 'YYYY-MM-DD')
  AND PASLIBRE LIKE 'x';