--NOMBRES JOURS
SELECT TO_DATE('2020-03-12','YYYY-MM-DD') - TO_DATE('2020-03-11','YYYY-MM-DD') + 1 AS "NBJOURS" FROM DUAL;

--REQUETE (ON SUPPOSE NBJOURS = 2 et NBKMS = 50)
SELECT TARIF_JOUR * 2  AS "JOUR", TARIF_HEBDO * 0 AS "SEMAINE", TARIF_KIL * 50 AS "KIL", TARIF_ASUR * 2 AS "ASSUR" FROM CATEGORIE C INNER JOIN VEHICULE V ON C.CODE_CATEG = V.CODE_CATEG INNER JOIN TARIF T ON C.CODE_TARIF = T.CODE_TARIF WHERE MODELE LIKE 'xantia2.0';