SELECT A.CODE_AG, A.RUE, A.VILLE, A.CODPOSTAL
FROM VEHICULE V
         INNER JOIN AGENCE A ON V.CODE_AG = A.CODE_AG
HAVING COUNT(DISTINCT CODE_CATEG) = (SELECT COUNT(CODE_CATEG) FROM CATEGORIE)
GROUP BY A.CODE_AG, A.RUE, A.VILLE, A.CODPOSTAL