SELECT A.CODE_AG
FROM VEHICULE V
         INNER JOIN AGENCE A on A.CODE_AG = V.CODE_AG
HAVING COUNT(DISTINCT CODE_CATEG) = (SELECT COUNT(*) FROM CATEGORIE)
GROUP BY A.CODE_AG;

--SELECT A.CODE_AG FROM VEHICULE V INNER JOIN AGENCE A on A.CODE_AG = V.CODE_AG having CODE_CATEG in ('c1','c2','c3');
